apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: control-plane
  sources:
    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.15.2
      helm:
        valueFiles:
          - $values/clusters/dev/apps/metallb/values.yaml

    # Source 2: your CRs (pool/advertisement) from THIS repo
    - repoURL: GIT_REPO_URL
      targetRevision: HEAD
      path: clusters/dev/apps/metallb/config

    # Source 3: values file (so we can reference it with $values/)
    - repoURL: GIT_REPO_URL
      targetRevision: HEAD
      ref: values

  destination:
    name: in-cluster
    namespace: metallb-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
