---
# Source: control-plane-launch/templates/10-networking/metallb.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: metallb-system
  source:
    repoURL: https://github.com/pukar10/metallb-launch.git
    targetRevision: main
    path: helm
    helm:
      releaseName: metallb
      valuesObject: 
        metallb:
          addresses:
          - 192.168.1.230-192.168.1.250
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
# Source: control-plane-launch/templates/20-core/argocd.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://github.com/pukar10/argocd-launch.git
    targetRevision: main
    path: helm
    helm:
      releaseName: argocd
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
# Source: control-plane-launch/templates/control-plane.yaml
# apps/parent.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: control-plane
  namespace: argocd
spec:
  project: default
  destination:
    name: in-cluster
    namespace: argocd
  source:
    repoURL: https://github.com/pukar10/control-plane-launch.git
    targetRevision: main
    path: .
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
