metallb:
  syncWave: -5
  values:
    addresses:
      - 192.168.1.230-192.168.1.250

ingressnginx:
  syncWave: -4
  values:
    controller:
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 192.168.1.230
    argocdIngress:
      enabled: true
      hosts: argocd.lab
      ingressClassName: nginx
      syncWave: "0"

certmanager:
  syncWave: -3
  values:
    certificate:
        host: argocd.lab

argocd:
  syncWave: -4
  values:
    server:
      ingress:
        hosts: [ "argocd.lab" ]
        tls:
          - hosts: [ "argocd.lab" ]
            secretName: argocd-tls
    configs:
      cm:
        url: "https://argocd.lab"