apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.metallb.syncWave }}"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: metallb-system
  source:
    repoURL: https://github.com/pukar10/metallb-launch.git
    targetRevision: main
    path: helm
    helm:
      releaseName: metallb
      valuesObject: 
        metallb:
          {{- toYaml .Values.metallb.values | nindent 10 }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
