apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "{{ default 10 .Values.metallb.syncWave }}"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: metallb-system
  source:
    repoURL: https://github.com/pukar10/metallb-launch.git
    targetRevision: main
    path: helm
    helm:
      releaseName: metallb
      {{- with .Values.metallb.values }}
      valuesObject:
    {{ toYaml .Values.metallb.values | nindent 8 }}
      {{- end }}
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
