apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    name: in-cluster
    namespace: metallb-system
  source:
    repoURL: {{ .Values.metallb.repoURL | quote }}
    targetRevision: {{ .Values.metallb.targetRevision | quote }}
    path: helm
    helm:
      releaseName: metallb
      {{- with .Values.metallb.values }}
      valuesObject:
{{ toYaml . | nindent 8 }}
      {{- end }}
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: 
      - CreateNamespace=true
